### ISSUE TITLE
Ask questions!

### ISSUE THREAD

**Issue by ZhangAdjy** [GruffyPuffy/imutest#1]
hello Stefan!, When I looked at your code, there was one thing I didn't quite understand.  in imutest.cpp 285 rows ,that ry is Unit matrix, i don't know why ry is unit matrix? and if i want to transform all pointcloud to same coordinate system when Intel Realsense D435i is moving, what should i do ? Thanks!
I am not good at English, i am sorry if you can't understand  what i mean!

**Comment by GruffyPuffy** [comment]
Hrm...this was 3 years ago... :) Well, if I can remeber correctly it is because the IMU can only sense pitch and roll. The yaw is unknown and the transformation is only "correcting" the pitch and roll (i.e. untilting the cloud so that the "floor" is level). 
What you are talking about is probably best known under the name SLAM (google it!) and is a lot bigger problem than what can be solved in such as small sample as this. Anyhow...good luck.
